# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9982e92e01bae69915dbff7274168288"
name = "bulk-pricing-function"
handle = "bulk-pricing-function"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "quickstart-38be6d81.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
